name: ruff
description: Run Ruff for linting and formatting Python code

on:
  push:
    branches:
      - main
  pull_request:
    types: [reopened, ready_for_review]

jobs:
  ruff :
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: 'check --fix --output-format=github'

    - name: Run Ruff formatter
      uses: astral-sh/ruff-action@v3
      with:
        args: 'format --check'